name: Release

on:
  release:
    types: [published]

jobs:
  sigstore-python:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: sigstore/gh-action-sigstore-python@v3.0.0
        with:
          release-signing-artifacts: true
          upload-signing-artifacts: true
